### ISSUE TITLE
missing property: gap

### ISSUE THREAD

**Issue by cotneit** [chaucerbao/stylelint-config-concentric-order#10]
gap property is missing

https://developer.mozilla.org/en-US/docs/Web/CSS/gap

**Comment by chaucerbao** [comment]
Thanks!

https://github.com/chaucerbao/stylelint-config-concentric-order/commit/57ec1e87981e684cfbdbfe3993aa768f8bed6a8e

**Comment by chaucerbao** [comment]
I noticed that the scope for `column-gap` has increased affect Flexbox and Grid, which makes its current position in the list a little awkward. I'm considering moving this grouping

```
  ['align-content', 'align-items', 'align-self'],
  ['justify-content', 'justify-items', 'justify-self'],
  ['order'],
```

below the "column" grouping.

**Comment by cotneit** [comment]
I think it's better to keep those close to Grid and Flexbox properties since they're not related to any of the properties inside the 'column' group. Might be a good idea to instead separate 'gap' properties into their own group.
There's also ['row-gap'](https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap) property to consider that also seems to be missing.

**Comment by chaucerbao** [comment]
With the current ordering, you would get:
```
grid;
row-gap;
align-items;
justify-content;
column-gap;
```
Which is awkward, because `row-gap` and `column-gap` are separated.

But if I move [this group](https://github.com/chaucerbao/stylelint-config-concentric-order/issues/10#issuecomment-750694064), you would get:
```
grid;
row-gap;
column-gap;
align-items;
justify-content;
```
Which makes more sense.

Even though they're not related, in general you would only be using one of the 3 layout options (`flex` or `grid` or `column`). So this move keeps the result in a meaningful order.
