### ISSUE TITLE
It's missing the 'will-change' property

### ISSUE THREAD

**Issue by daviddelusenet** [chaucerbao/stylelint-config-concentric-order#2]
The `will-change` property is missing.

**Comment by chaucerbao** [comment]
Sorry, I totally missed this issue.

Since Concentric CSS is about ordering properties by the CSS Box Model, and the `will-change` property doesn't have any visual impact (since it's just an optimization [hint](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)), it will be filed under [unspecified](https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-order/README.md#optional-secondary-options), which is `ignore` by default (leaves it in-place).

At one point, I had `unspecified` properties [sorted at the bottom](https://github.com/chaucerbao/stylelint-config-concentric-order/commit/0499e6a1fbf393f0ec90e3c618e301d3b18896f5#diff-1fdf421c05c1140f6d71444ea2b27638L212), but ran into issues with [styled-components](https://www.styled-components.com/), so `ignore` was the best option there.

**Comment by chaucerbao** [comment]
Although it might not fit into Concentric CSS, I can definitely see why you'd want it sorted consistently in a project.

I'll add it towards the bottom.

**Comment by chaucerbao** [comment]
Done
